dotNetMVC/webMVC/Controllers/AbsentController.cs
using Microsoft.AspNetCore.Mvc;
using webMVC.Models;

namespace webMVC.Controllers
{
    public class AbsentController : Controller
    {
        private static List<AbsentViewModel> _absentViewModels = new List<AbsentViewModel>()
        {
            new AbsentViewModel(1, 1001, "Irvan", "Laki-laki", "CEO"),
            new AbsentViewModel(2, 1002, "Reza", "Laki-laki", "CFO"),
            new AbsentViewModel(3, 1003, "Fatima", "Perempuan", "CTO"),
            new AbsentViewModel(4, 1004, "Ariza", "Perempuan", "COO"),
        };

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Add() 
        { 
            return View();
        }

        public IActionResult List()
        {
            return View(_absentViewModels);
        }

        [HttpPost]
        public IActionResult Save([Bind("Id, NIK, Nama, JenisKelamin, Jabatan")] AbsentViewModel absent)
        {
            _absentViewModels.Add(absent);
            return Redirect("List");
        }

        public IActionResult Edit(int? id)
        {
            AbsentViewModel absent = _absentViewModels.Find(x => x.Id.Equals(id));
            return View(absent);
        }

        [HttpPost]
        public IActionResult Update(int id, [Bind("Id, NIK, Nama, JenisKelamin, Jabatan")] AbsentViewModel absent)
        {
            AbsentViewModel absentOld = _absentViewModels.Find(x => x.Id.Equals(id));
            _absentViewModels.Remove(absentOld);

            _absentViewModels.Add(absent);
            return Redirect("List");
        }

        public IActionResult Details(int id)
        {
            AbsentViewModel absent = (
                from a in _absentViewModels
                where a.Id.Equals(id)
                select a
                ).SingleOrDefault(new AbsentViewModel());
            return View(absent);
        }

        public IActionResult Delete(int? id)
        {
            AbsentViewModel absent = _absentViewModels.Find(x => x.Id.Equals(id));
            _absentViewModels.Remove(absent);

            return View(absent);
        }
    }
}

dotNetMVC/webMVC/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using webMVC.Models;

namespace webMVC.Controllers
{
    public class AdminController : Controller
    {
        private static List<AdminViewModel> _adminViewModels = new List<AdminViewModel>()
        {
            new AdminViewModel(1, "Admin Irvan", 2856234, "Laki-laki", "Admin HR"),
            new AdminViewModel(2, "Admin Reza", 2752875, "Laki-laki", "Admin HR"),
            new AdminViewModel(3, "Admin Fatima", 2554836, "Perempuan", "Admin HR"),
            new AdminViewModel(4, "Admin Tertia", 2576534, "Perempuan", "Admin HR"),
            new AdminViewModel(5, "Admin Arizaz", 2097124, "Perempuan", "Admin HR"),
        };
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Add()
        {
            return View();
        }
        public IActionResult List()
        {
            return View(_adminViewModels);
        }

        [HttpPost]
        public IActionResult Save([Bind("Id, Nama, NIK, JenisKelamin, Position")] AdminViewModel admin)
        {
            _adminViewModels.Add(admin);
            return Redirect("List");
        }

        public IActionResult Edit(int? id)
        {
            AdminViewModel admin = _adminViewModels.Find(x => x.Id.Equals(id));
            return View(admin);
        }

        [HttpPost]
        public IActionResult Update(int id, [Bind("Id, Nama, NIK, JenisKelamin, Position")] AdminViewModel admin)
        {
            AdminViewModel adminOld = _adminViewModels.Find(x => x.Id.Equals(id));
            _adminViewModels.Remove(adminOld);

            _adminViewModels.Add(admin);
            return Redirect("List");
        }

        public IActionResult Details(int id)
        {
            AdminViewModel admin = (
                from a in _adminViewModels
                where a.Id.Equals(id)
                select a
                ).SingleOrDefault(new AdminViewModel());
            return View(admin);
        }

        public IActionResult Delete(int? id)
        {
            AdminViewModel admin = _adminViewModels.Find(x => x.Id.Equals(id));
            _adminViewModels.Remove(admin);

            return View(admin);
        }
    }
}

dotNetMVC/webMVC/Controllers/AuditController.cs
using Microsoft.AspNetCore.Mvc;
using webMVC.Models;

namespace webMVC.Controllers
{
    public class AuditController : Controller
    {
        private static List<AuditViewModel> _auditViewModels = new List<AuditViewModel>()
        {
            new AuditViewModel(1, 2001, "Acer 9", "i7", "K264GS", "Irvan", "Windows 11", "Office 2019"),
            new AuditViewModel(2, 2002, "HP 7", "i3", "J47SG4", "Fahreza", "Windows 8", "Office 2017"),
            new AuditViewModel(3, 2003, "Acer 25", "i5", "SHG85H", "Fatima", "Windows 11", "Office 2017"),
            new AuditViewModel(4, 2004, "ROG 6", "i9", "SGF782", "Tertia", "Windows 10", "Office 2021"),
            new AuditViewModel(5, 2005, "Dell 2", "i9", "HSGG92", "Ariza", "Windows 11", "Office 2019"),
        };

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Add()
        {
            return View();
        }

        public IActionResult List()
        {
            return View(_auditViewModels);
        }

        [HttpPost]
        public IActionResult Save([Bind("Id, AssetNo, AssetName, AssetType, SerialNo, PIC, TypeWindows, TypeOffice")] AuditViewModel audit)
        {
            _auditViewModels.Add(audit);
            return Redirect("List");
        }

        public IActionResult Edit(int? id)
        {
            AuditViewModel audit = _auditViewModels.Find(x => x.Id.Equals(id));
            return View(audit);
        }

        [HttpPost]
        public IActionResult Update(int id, [Bind("Id, AssetNo, AssetName, AssetType, SerialNo, PIC, TypeWindows, TypeOffice")] AuditViewModel audit)
        {
            AuditViewModel auditOld = _auditViewModels.Find(x => x.Id.Equals(id));
            _auditViewModels.Remove(auditOld);

            _auditViewModels.Add(audit);
            return Redirect("List");
        }

        public IActionResult Details(int id)
        {
            AuditViewModel audit = (
                from a in _auditViewModels
                where a.Id.Equals(id)
                select a
                ).SingleOrDefault(new AuditViewModel());
            return View(audit);
        }

        public IActionResult Delete(int? id)
        {
            AuditViewModel audit = _auditViewModels.Find(x => x.Id.Equals(id));
            _auditViewModels.Remove(audit);

            return View(audit);
        }
    }
}

dotNetMVC/webMVC/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using webMVC.Models;

namespace webMVC.Controllers
{
    public class UsersController : Controller
    {
        private static List<UsersViewModel> _usersViewModels = new List<UsersViewModel>()
        {
            new UsersViewModel(1, "Irvan", 22947234, "Surabaya", "Backend Developer"),
            new UsersViewModel(2, "Reza", 27492058, "Jakarta", "Backend Developer"),
            new UsersViewModel(3, "Fatima", 93755634, "Palembang", "Frontend Developer"),
            new UsersViewModel(4, "Tertia", 98476234, "Bandung", "Frontend Developer"),
            new UsersViewModel(5, "Ariza", 76500474, "Medan", "QA Analyst"),
        };
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Add()
        {
            return View();
        }

        public IActionResult List()
        {
            return View(_usersViewModels);
        }

        [HttpPost]
        public IActionResult Save([Bind("Id, Nama, NIK, TempatLahir, JobPosition")] UsersViewModel users)
        {
            _usersViewModels.Add(users);
            return Redirect("List");
        }
        public IActionResult Edit(int? id)
        {
            UsersViewModel users = _usersViewModels.Find(x => x.Id.Equals(id));
            return View(users);
        }
        [HttpPost]
        public IActionResult Update(int id, [Bind("Id, Nama, NIK, TempatLahir, JobPosition")] UsersViewModel users)
        {
            UsersViewModel usersOld = _usersViewModels.Find(x => x.Id.Equals(id));
            _usersViewModels.Remove(usersOld);

            _usersViewModels.Add(users);
            return Redirect("List");
        }
        public IActionResult Details(int id)
        {
            UsersViewModel users= (
                from u in _usersViewModels
                where u.Id.Equals(id)
                select u
                ).SingleOrDefault(new UsersViewModel());
            return View(users);
        }
        public IActionResult Delete(int? id)
        {
            UsersViewModel users = _usersViewModels.Find(x => x.Id.Equals(id));
            _usersViewModels.Remove(users);

            return View(users);
        }
    }
}

dotNetMVC/webMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - dotNET webMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/webMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">dotNET webMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="nav nav-tabs flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Absent" asp-action="Index">Absent</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Inventory" asp-action="Index">Inventory</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Audit" asp-action="Index">Audit</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
                        </li>

                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ContactUs">Contact Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="News">News</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Projects">Project</a>
                        </li>*@
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Products">Products</a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    @*<div class="flex-shrink-0 p-3 bg-white" style="width: 280px;">
    <a href="/" class="d-flex align-items-center pb-3 mb-3 link-dark text-decoration-none border-bottom">
      <span class="fs-5 fw-semibold">Sidebar</span>
    </a>
    <ul class="list-unstyled ps-0">
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded" data-bs-toggle="collapse" data-bs-target="#home-collapse" aria-expanded="true">
          Home
        </button>
        <div class="collapse show" id="home-collapse" style="">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a class="nav-link active" asp-area="" asp-controller="Product" asp-action="Index">Product</a></li>
            <li><a class="nav-link text-dark" asp-area="" asp-controller="Absent" asp-action="Index">Absent</a></li>
            <li><a class="nav-link text-dark" asp-area="" asp-controller="Inventory" asp-action="Index">Inventory</a></li>
            <li><a class="nav-link text-dark" asp-area="" asp-controller="Audit" asp-action="Index">Audit</a></li>
            <li><a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a></li>
            <li><a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a></li>
          </ul>
        </div>
      </li>
      </ul>
      </div>*@

    @*<div class="d-flex flex-column flex-shrink-0 p-3 bg-light" style="width: 280px;">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
            <span class="fs-4">dotNET webMVC</span>
        </a>
        <hr>
        <ul class="nav nav-tabs flex-column mb-auto">
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
            </li>
            <li>
                <a class="nav-link text-dark" asp-area="" asp-controller="Absent" asp-action="Index">Absent</a>
            </li>
            <li>
                <a class="nav-link text-dark" asp-area="" asp-controller="Inventory" asp-action="Index">Inventory</a>
            </li>
            <li>
                <a class="nav-link text-dark" asp-area="" asp-controller="Audit" asp-action="Index">Audit</a>
            </li>
            <li>
                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
            </li>
            <li>
                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
            </li>
        </ul>
    </div>*@

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Irvan Fahreza - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>